name: Build

on: [push]

env:
  PORTAUDIO_ROOT: src/portaudio
  ASIO_ROOT: src/ASIOSDK
  pkg_dest: build/
  log_dest: build-logs/

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        build_config: ['Release', 'Debug']
        build_platform: ['Win32', 'x64']

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Download sources
      run: python get_sources.py

    - shell: bash
      run: cp -R $ASIO_ROOT $PORTAUDIO_ROOT/src/hostapi/asio/

    - name: MSBuild
      run: msbuild src\portaudio\build\msvc\portaudio.sln /property:Configuration=${{ matrix.build_config }} /property:Platform=${{ matrix.build_platform }}

    - name: Gather outputs
      run: python gather_outputs.py --pkg-dest ${{ pkg_dest }} --log-dest ${{ log_dest }} --src-root ${{ PORTAUDIO_ROOT }} --platform ${{ matrix.build_platform }} --config ${{ matrix.build_config }}

    - uses: actions/upload-artifact@v1
      with:
        name: logs-${{ matrix.build_platform }}-${{ matrix.build_config }}
        path: ${{ log_dest }}

    - uses: actions/upload-artifact@v1
      with:
        name: portaudio-${{ matrix.build_platform }}-${{ matrix.build_config }}
        path: ${{ pkg_dest }}
